src/AbpCompanyName.AbpProjectName.Core/AbpCompanyName.AbpProjectName.Core.csproj, src/AbpCompanyName.AbpProjectName.Core/Localization/Source/AbpProjectName.xml, src/AbpCompanyName.AbpProjectName.WebSpaAngular/AbpCompanyName.AbpProjectName.WebSpaAngular.csproj, src/AbpCompanyName.AbpProjectName.WebSpaAngular/App/Main/views/layout/header.cshtml, src/AbpCompanyName.AbpProjectName.WebSpaAngular/Controllers/AccountController.cs, src/AbpCompanyName.AbpProjectName.WebSpaAngular/Models/Account/ChangePasswordViewModel.cs, src/AbpCompanyName.AbpProjectName.WebSpaAngular/Views/Account/ChangePassword.cshtml, src/AbpCompanyName.AbpProjectName.WebSpaAngular/Views/Account/Login.cshtml
The ChangePassword View is designed to be loaded inside a modal popup. 
I went for this approach: http://www.codeproject.com/Tips/826002/Bootstrap-Modal-Dialog-Loading-Content-from-MVC-Pa 
But other implementations should be possible as well (including implementation with WebApi).
=> Change Password ViewModel, PartialView and AccountController methods

src/AbpCompanyName.AbpProjectName.Core/Localization/Source/AbpProjectName-pt-BR.xml, src/AbpCompanyName.AbpProjectName.EntityFramework/Migrations/SeedData/DefaultLanguagesBuilder.cs
=> PT-BR Translation

src/AbpCompanyName.AbpProjectName.Core/AbpCompanyName.AbpProjectName.Core.csproj, src/AbpCompanyName.AbpProjectName.Core/Localization/Source/AbpProjectName-ja.xml, src/AbpCompanyName.AbpProjectName.EntityFramework/Migrations/SeedData/DefaultLanguagesCreator.cs
i created japanese translation file.
please merge.
thank you.
=> Add japanese

src/AbpCompanyName.AbpProjectName.Core/AbpCompanyName.AbpProjectName.Core.csproj, src/AbpCompanyName.AbpProjectName.Core/Localization/Source/AbpProjectName-nl-NL.xml, src/AbpCompanyName.AbpProjectName.EntityFramework/Migrations/SeedData/DefaultLanguagesCreator.cs
Added Dutch language file and the line of code to add the language to the database table on intitial seed.
=> Added Dutch language

src/AbpCompanyName.AbpProjectName.Core/Localization/Source/AbpProjectName-it.xml
Fixed some words that weren't correct in italian language.
=> Fixed italian's translation

src/AbpCompanyName.AbpProjectName.Core/Localization/Source/AbpProjectName-lt.xml
=> Updated Lithuanian translations

src/AbpCompanyName.AbpProjectName.WebSpaAngular/App/Main/views/layout/sidebar-nav.cshtml
Fixes https://stackoverflow.com/questions/46925119/could-not-resolve-submenuitem-route-from-state-datapoint
=> Fix AngularJS expressions in sidebar-nav.cshtml

src/AbpCompanyName.AbpProjectName.Application/Users/UserAppService.cs
Fixes https://github.com/aspnetboilerplate/aspnetboilerplate/issues/2749
=> Save changes to set Id in DTO when creating user

src/AbpCompanyName.AbpProjectName.Application/app.config, src/AbpCompanyName.AbpProjectName.Core/app.config, src/AbpCompanyName.AbpProjectName.EntityFramework/App.config, src/AbpCompanyName.AbpProjectName.WebApi/app.config, src/AbpCompanyName.AbpProjectName.WebMpa/Web.config, src/AbpCompanyName.AbpProjectName.WebSpaAngular/Web.config, src/Tests/AbpCompanyName.AbpProjectName.Tests/App.config, src/Tools/AbpCompanyName.AbpProjectName.Migrator/App.config
Fixes https://github.com/aspnetboilerplate/aspnetboilerplate/issues/2902
Fixes https://github.com/aspnetboilerplate/aspnetboilerplate/issues/3881
First reported on Jan 10, fix proposed on Jan 11:
https://stackoverflow.com/questions/48179819/asp-net-boilerplate-mvc-5-x-template-fails-to-start
=> Remove unnecessary bindingRedirect for Castle.Core

src/AbpCompanyName.AbpProjectName.WebMpa/AbpCompanyName.AbpProjectName.WebMpa.csproj, src/AbpCompanyName.AbpProjectName.WebMpa/Web.config, src/AbpCompanyName.AbpProjectName.WebMpa/packages.config
Include jquery.serializejson to project because it is use it in
=> Include jquery.serializejson to project because it is use it in

src/AbpCompanyName.AbpProjectName.EntityFramework/Migrations/SeedData/DefaultLanguagesCreator.cs
Repair flag class but wrong class is in documentation too. Please can you correct it.
https://aspnetboilerplate.com/Pages/Documents/Localization
=> Repair famfamfam-flags

src/AbpCompanyName.AbpProjectName.Application/AbpProjectNameAppServiceBase.cs
fix awaiting to get current user, because not waiting a result and not throwing exception
=> fix awaiting to get current user, because not waiting a result

src/AbpCompanyName.AbpProjectName.WebMpa/Views/Account/_TenantChange.js, src/AbpCompanyName.AbpProjectName.WebMpa/Views/Roles/Index.js, src/AbpCompanyName.AbpProjectName.WebMpa/Views/Tenants/Index.js, src/AbpCompanyName.AbpProjectName.WebMpa/Views/Users/Index.js
Resolve https://github.com/aspnetboilerplate/aspnetboilerplate/issues/4139
=> Replace jquery ajax with abp ajax

src/AbpCompanyName.AbpProjectName.Application/AbpProjectNameApplicationModule.cs, src/AbpCompanyName.AbpProjectName.Application/Roles/Dto/CreateRoleDto.cs, src/AbpCompanyName.AbpProjectName.Application/Roles/Dto/RoleDto.cs, src/AbpCompanyName.AbpProjectName.Application/Roles/RoleAppService.cs, src/AbpCompanyName.AbpProjectName.WebMpa/Models/Roles/EditRoleModalViewModel.cs, src/AbpCompanyName.AbpProjectName.WebMpa/Views/Roles/Index.js, src/AbpCompanyName.AbpProjectName.WebMpa/Views/Roles/_EditRoleModal.js, src/AbpCompanyName.AbpProjectName.WebSpaAngular/App/Main/views/roles/createModal.js, src/AbpCompanyName.AbpProjectName.WebSpaAngular/App/Main/views/roles/editModal.js
Resolve https://github.com/aspnetboilerplate/aspnetboilerplate/issues/4861
=> Use GrantedPermissions instead of Permissions in Role.

src/AbpCompanyName.AbpProjectName.WebMpa/Views/Account/_TenantChange.js, src/AbpCompanyName.AbpProjectName.WebMpa/Views/Roles/Index.js, src/AbpCompanyName.AbpProjectName.WebMpa/Views/Tenants/Index.js, src/AbpCompanyName.AbpProjectName.WebMpa/Views/Users/Index.js, src/AbpCompanyName.AbpProjectName.WebSpaAngular/Views/Account/_TenantChange.js
Resolve https://github.com/aspnetboilerplate/aspnetboilerplate/issues/4889
=> Override abp.ajax default dataType.

src/AbpCompanyName.AbpProjectName.WebMpa/Views/UrlChecker.cs
Fixed the IsRooted method to include urls starting with "~/".
I found it useful as original code did not include root urls starting with ~
=> Fixed the IsRooted method

src/AbpCompanyName.AbpProjectName.WebMpa/Views/Tenants/Index.js
Tenant delete button shows JS code instead of deleting tenant.
Title parameter is missing in function call to confirm method.
=> Update to tenant management screen

src/AbpCompanyName.AbpProjectName.Application/AbpCompanyName.AbpProjectName.Application.csproj, src/AbpCompanyName.AbpProjectName.Application/packages.config, src/AbpCompanyName.AbpProjectName.Core/AbpCompanyName.AbpProjectName.Core.csproj, src/AbpCompanyName.AbpProjectName.Core/packages.config, src/AbpCompanyName.AbpProjectName.EntityFramework/AbpCompanyName.AbpProjectName.EntityFramework.csproj, src/AbpCompanyName.AbpProjectName.EntityFramework/packages.config, src/AbpCompanyName.AbpProjectName.WebApi/AbpCompanyName.AbpProjectName.WebApi.csproj, src/AbpCompanyName.AbpProjectName.WebApi/packages.config, src/AbpCompanyName.AbpProjectName.WebMpa/AbpCompanyName.AbpProjectName.WebMpa.csproj, src/AbpCompanyName.AbpProjectName.WebMpa/packages.config, src/AbpCompanyName.AbpProjectName.WebSpaAngular/AbpCompanyName.AbpProjectName.WebSpaAngular.csproj, src/AbpCompanyName.AbpProjectName.WebSpaAngular/packages.config, src/Tests/AbpCompanyName.AbpProjectName.Tests/AbpCompanyName.AbpProjectName.Tests.csproj, src/Tests/AbpCompanyName.AbpProjectName.Tests/packages.config, src/Tools/AbpCompanyName.AbpProjectName.Migrator/AbpCompanyName.AbpProjectName.Migrator.csproj, src/Tools/AbpCompanyName.AbpProjectName.Migrator/packages.config
related https://github.com/aspnetboilerplate/aspnetboilerplate/issues/5988
=> Upgrade abp packages

src/AbpCompanyName.AbpProjectName.Core/AbpProjectNameConsts.cs, src/AbpCompanyName.AbpProjectName.Core/AbpProjectNameCoreModule.cs
The {{DEFAULT_PASS_PHRASE_HERE}} placeholder will be replaced by website when the project is downloaded.
related https://github.com/aspnetboilerplate/aspnetboilerplate/issues/6048
=> change DefaultPassPhrase for every project

src/AbpCompanyName.AbpProjectName.Application/AbpCompanyName.AbpProjectName.Application.csproj, src/AbpCompanyName.AbpProjectName.Application/packages.config, src/AbpCompanyName.AbpProjectName.Core/AbpCompanyName.AbpProjectName.Core.csproj, src/AbpCompanyName.AbpProjectName.Core/packages.config, src/AbpCompanyName.AbpProjectName.EntityFramework/AbpCompanyName.AbpProjectName.EntityFramework.csproj, src/AbpCompanyName.AbpProjectName.EntityFramework/packages.config, src/AbpCompanyName.AbpProjectName.WebApi/AbpCompanyName.AbpProjectName.WebApi.csproj, src/AbpCompanyName.AbpProjectName.WebApi/app.config, src/AbpCompanyName.AbpProjectName.WebApi/packages.config, src/AbpCompanyName.AbpProjectName.WebMpa/AbpCompanyName.AbpProjectName.WebMpa.csproj, src/AbpCompanyName.AbpProjectName.WebMpa/Web.config, src/AbpCompanyName.AbpProjectName.WebMpa/packages.config, src/AbpCompanyName.AbpProjectName.WebSpaAngular/AbpCompanyName.AbpProjectName.WebSpaAngular.csproj, src/AbpCompanyName.AbpProjectName.WebSpaAngular/Web.config, src/AbpCompanyName.AbpProjectName.WebSpaAngular/packages.config, src/Tests/AbpCompanyName.AbpProjectName.Tests/AbpCompanyName.AbpProjectName.Tests.csproj, src/Tests/AbpCompanyName.AbpProjectName.Tests/packages.config, src/Tools/AbpCompanyName.AbpProjectName.Migrator/AbpCompanyName.AbpProjectName.Migrator.csproj, src/Tools/AbpCompanyName.AbpProjectName.Migrator/packages.config
related https://github.com/aspnetboilerplate/aspnetboilerplate/issues/6203
=> Upgrade to ABP 6.4.0

src/AbpCompanyName.AbpProjectName.Application/AbpCompanyName.AbpProjectName.Application.csproj, src/AbpCompanyName.AbpProjectName.Application/packages.config, src/AbpCompanyName.AbpProjectName.Core/AbpCompanyName.AbpProjectName.Core.csproj, src/AbpCompanyName.AbpProjectName.Core/Authorization/Users/UserManager.cs, src/AbpCompanyName.AbpProjectName.Core/packages.config, src/AbpCompanyName.AbpProjectName.EntityFramework/AbpCompanyName.AbpProjectName.EntityFramework.csproj, src/AbpCompanyName.AbpProjectName.EntityFramework/packages.config, src/AbpCompanyName.AbpProjectName.WebApi/AbpCompanyName.AbpProjectName.WebApi.csproj, src/AbpCompanyName.AbpProjectName.WebApi/packages.config, src/AbpCompanyName.AbpProjectName.WebMpa/Abp/Framework/scripts/abp.d.ts, src/AbpCompanyName.AbpProjectName.WebMpa/AbpCompanyName.AbpProjectName.WebMpa.csproj, src/AbpCompanyName.AbpProjectName.WebMpa/packages.config, src/AbpCompanyName.AbpProjectName.WebSpaAngular/Abp/Framework/scripts/abp.d.ts, src/AbpCompanyName.AbpProjectName.WebSpaAngular/AbpCompanyName.AbpProjectName.WebSpaAngular.csproj, src/AbpCompanyName.AbpProjectName.WebSpaAngular/packages.config, src/Tests/AbpCompanyName.AbpProjectName.Tests/AbpCompanyName.AbpProjectName.Tests.csproj, src/Tests/AbpCompanyName.AbpProjectName.Tests/packages.config, src/Tools/AbpCompanyName.AbpProjectName.Migrator/AbpCompanyName.AbpProjectName.Migrator.csproj, src/Tools/AbpCompanyName.AbpProjectName.Migrator/packages.config
related https://github.com/aspnetboilerplate/aspnetboilerplate/issues/6385
=> Upgrade to Abp 7.1.0

src/AbpCompanyName.AbpProjectName.Core/Localization/Source/AbpProjectName-lt.xml
Added missing translation string.
=> Updated Lithuanian translations on template
